trigger: none
pool: 'analytics-ops-agents'


resources:
  repositories:
    - repository: 'pipelines'
      type: 'git'
      name: 'AnalyticsOps/pipelines'
      path: 'pipelines'
      ref: 'refs/tags/v3.2'


parameters:

  # Name of project must be less than X charecters
  - name: projectName
    default: '{{ projectName }}'
    type: string

  # Unique resource number change this if you make multiple deployements of the same setup
  - name: resourceNumber
    default: '1'
    type: string

  # Model version is visible in Azure ML Studio on the "Models" page
  - name: modelVersion
    type: string


stages:

  - template: pipelines/model/build-and-deploy.yml@pipelines
    parameters:
      projectName: ${{ parameters.projectName }}
      resourceNumber: ${{ parameters.resourceNumber }}
      mlServiceConnection: 'analyticsops-irisdemo-D'
      mlResourceGroup: 'analyticsops-irisdemo-D'
      mlModelVersion: ${{ parameters.modelVersion }}
      crServiceConnection: 'analyticsops-irisdemo-D'
      environments:
        - name: 'dev'
          serviceConnection: 'analyticsops-irisdemo-D'
        - name: 'prod'
          serviceConnection: 'analyticsops-irisdemo-P'
