trigger: none
pool: 'analytics-ops-agents'


resources:
  repositories:
    - repository: 'pipelines'
      type: 'git'
      name: 'AnalyticsOps/pipelines'
      path: 'pipelines'
      ref: 'refs/tags/v3.4'


parameters:

  # Name of project must be less than X charecters
  - name: projectName
    default: '{{ projectName }}'
    type: string

  # Unique resource number change this if you make multiple deployements of the same setup
  - name: resourceNumber
    default: '1'
    type: string


stages:

  - template: pipelines/deploy/model/build-and-deploy.yml@pipelines
    parameters:
{% raw %}
      projectName: ${{ parameters.projectName }}
      resourceNumber: ${{ parameters.resourceNumber }}
{% endraw %}
      crServiceConnection: '{{ serviceConnection }}'
      environments:
        - name: 'dev'
          serviceConnection: '{{ serviceConnection }}'
